export const CLICK_NUM  = 'day2/CLICK_NUM'
export const CLEAR_NUM  = 'day2/CLEAR_NUM'
export const ADD_DECIMALS  = 'day2/ADD_DECIMALS'
export const BREAK_UP  = 'day2/BREAK_UP'
export const OPERATOR  = 'day2/OPERATOR'